-- TagLingo — Phase 2: seed vocabulary from docs/taglingo_words_template.csv
-- 23 starter words: Beginner 10 · Intermediate 8 · Advanced 5.
--
-- GENERATED by scripts/generate-words-seed.mjs — do not edit by hand;
-- edit the CSV and re-run `node scripts/generate-words-seed.mjs --write`.
--
-- Applies ONCE (Supabase CLI tracks applied migrations). Words are read-only
-- for clients; this migration is the only write path until a service-role
-- import expands the dataset toward the 200–300 target (Phase 6).

insert into public.words (tagalog, cebuano, english, level, example_sentence, audio_url)
values
  -- beginner (10)
  ('isa', 'usa', 'one', 'Beginner', NULL, NULL),
  ('dalawa', 'duha', 'two', 'Beginner', NULL, NULL),
  ('pamilya', 'pamilya', 'family', 'Beginner', NULL, NULL),
  ('kumain', 'mokaon', 'to eat', 'Beginner', NULL, NULL),
  ('tubig', 'tubig', 'water', 'Beginner', NULL, NULL),
  ('bahay', 'balay', 'house', 'Beginner', NULL, NULL),
  ('aso', 'iro', 'dog', 'Beginner', NULL, NULL),
  ('kumusta', 'kumusta', 'hello', 'Beginner', NULL, NULL),
  ('salamat', 'salamat', 'thank you', 'Beginner', NULL, NULL),
  ('pula', 'pula', 'red', 'Beginner', NULL, NULL),
  -- intermediate (8)
  ('trabaho', 'trabaho', 'work', 'Intermediate', NULL, NULL),
  ('kaligayahan', 'kalipay', 'happiness', 'Intermediate', NULL, NULL),
  ('maglakad', 'maglakaw', 'to walk', 'Intermediate', NULL, NULL),
  ('kapatid', 'igsoon', 'sibling', 'Intermediate', NULL, NULL),
  ('paaralan', 'eskwelahan', 'school', 'Intermediate', NULL, NULL),
  ('tulungan', 'tabangan', 'to help', 'Intermediate', NULL, NULL),
  ('pagkakataon', 'higayon', 'opportunity', 'Intermediate', NULL, NULL),
  ('malungkot', 'masulub-on', 'sad', 'Intermediate', NULL, NULL),
  -- advanced (5)
  ('pananagutan', 'responsibilidad', 'responsibility', 'Advanced', NULL, NULL),
  ('kasarinlan', 'kagawasan', 'independence', 'Advanced', NULL, NULL),
  ('katarungan', 'hustisya', 'justice', 'Advanced', NULL, NULL),
  ('kalikasan', 'kinaiyahan', 'nature (environment)', 'Advanced', NULL, NULL),
  ('pagtitiyaga', 'pagpadayon', 'perseverance', 'Advanced', NULL, NULL);

-- Post-seed sanity check (should read the counts above per level):
--   select level, count(*) from public.words group by level order by level;
